name: stipra
description: Stipra application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+7

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  stacked: ^2.3.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter_screenutil: ^5.2.0
  google_fonts: ^2.1.1
  internet_connection_checker: ^0.0.1+3
  font_awesome_flutter: ^9.2.0
  intl_phone_number_input: ^0.7.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_glow: ^0.2.0
  email_validator: ^2.0.1
  pin_code_fields: ^7.3.0
  auto_size_text: ^3.0.0
  introduction_screen: ^3.0.0
  flutter_svg: ^1.0.3
  #mobile_scanner: ^1.0.0
  material_floating_search_bar: ^0.3.7
  carousel_slider: ^4.0.0
  dots_indicator: ^2.1.0
  path_provider: ^2.0.9
  #screen_recorder: ^0.0.3
  #flutter_foreground_plugin:
  #  git:
  #    url: https://github.com/jja08111/flutter_foreground_service_plugin
  #flutter_screen_recording:
  #  path: ./flutter_screen_recording
  rest_api_package:
    path: ./rest_api_package
  video_player: ^2.3.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  geolocator: ^8.2.0
  package_info_plus: ^1.4.0
  google_mlkit_commons:
    path: ./google_mlkit_commons
  google_mlkit_barcode_scanning:
    path: ./google_mlkit_barcode_scanning
  camera:
    path: ./camera
  flutter_vibrate: ^1.3.0
  connectivity_plus: ^2.2.1
  shared_preferences: ^2.0.13
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  flutter_keyboard_visibility: ^5.2.0
  dart_ipify: ^1.1.1
  flutter_image_compress: ^1.0.0
  image_picker: ^0.8.5
  gesture_x_detector: ^1.0.0
  dropdown_button2: ^1.4.0
  barcode_widget: ^2.0.2
  app_settings: ^4.1.5
  flutter_map: ^0.14.0
  ionicons: ^0.1.2
  flutter_sticky_header: ^0.6.1
  #camera: any
  jiffy: ^5.0.0
  video_thumbnail: ^0.5.0
  get: ^4.6.1
  cached_network_image: ^3.2.0
  lottie: ^1.3.0
  flutter_slidable: ^1.2.1
  fl_chart: ^0.50.6
  url_launcher: ^6.1.2
  d_chart: ^0.0.4
  pretty_gauge: ^1.0.1
  gauges: ^1.0.0

dependency_overrides:
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.0
  flutter_launcher_icons_maker: "^0.10.1"

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/icon/icon.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/lotties/
    - assets/images/board/
    - test/fixtures/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
